/**
 * Tray icon files.
 *
 * `systray2` takes `icon` as a **file path**, not as image data. Its `resolveIcon()`
 * calls `fs.pathExists(icon)`; when that resolves true it `readFile()`s the path and
 * `toString('base64')`s the bytes itself, and only then hands them to the tray binary.
 * A string that is already base64 is not a path, so `pathExists` is false, the string
 * is forwarded unchanged, and the native side receives data it cannot decode. The
 * binary's own source names the format it starts with:
 *
 *   iconBytes should be the content of .ico for windows and .ico/.jpg/.png for other
 *   platforms.
 *
 * So a bare PNG can never work on Windows, and this module hands `systray2` an
 * absolute path to a real file, choosing the extension for the platform: `.ico` on
 * Windows, `.png` on macOS/Linux. That mechanism, not just the conclusion, is the
 * reason the previous comment here ("raw base64 without the data: prefix") was wrong.
 *
 * The files are generated by `scripts/build-tray-icons.mjs` from
 * `src/ui/icons/tray-piece.svg`, which stays the single source of truth. Do not edit
 * a generated PNG/ICO by hand: edit the SVG and re-run the script. `normal` is the app
 * listening; `grey` is the watchdog's "the listener has gone quiet" state (DESIGN 7).
 * Colour is the state signal, the shape is the identity.
 */
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICON_DIR = join(dirname(fileURLToPath(import.meta.url)), 'icons');

/** The format Windows' `LoadImage` accepts that a rasteriser's PNG output is not. */
export function iconExtension(platform = process.platform) {
  return platform === 'win32' ? 'ico' : 'png';
}

/** Absolute path of one state's icon file for `platform`; unknown states fall back to `normal`. */
export function trayIconPath(state, platform = process.platform) {
  const name = state === 'grey' ? 'tray-grey' : 'tray-normal';
  return join(ICON_DIR, `${name}.${iconExtension(platform)}`);
}

/** Both state paths on the current platform, for callers that need the set. */
export const TRAY_ICONS = {
  normal: trayIconPath('normal'),
  grey: trayIconPath('grey'),
};

/** Icon path for a state name; unknown states fall back to `normal`. */
export function trayIcon(state) {
  return TRAY_ICONS[state] ?? TRAY_ICONS.normal;
}
