/**
 * Tray icon bitmaps.
 *
 * Two 16x16 PNGs of a jigsaw puzzle piece, embedded as base64 rather than generated
 * at runtime: the tray adapter must not pull `sharp` (or any image library) into the
 * always-on path just to colour a pixel. `normal` is the app listening; `grey` is the
 * watchdog's "the listener has gone quiet" state (DESIGN 7). Colour is the state
 * signal, the shape is the identity.
 *
 * Generated by `scripts/build-tray-icons.mjs` from `src/ui/icons/tray-piece.svg`.
 * Do not edit the base64 by hand: edit the SVG and re-run the script.
 *
 * `systray2` wants raw base64 without the `data:` prefix.
 */

const BLUE_PIECE_16 =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAADsOAAA7DgHMtqGDAAAA5ElEQVQ4jWNgoCmwr+cAY5KBazE3j0PVXm770l8gzONYtQckRrR+HoeyMgG/yd/kKm79B2EB/8nfuGxLSvBq4rQpzuKyKS4HY4fyy+Ip2//LVdwBY/Hkbf+57MsvweRBajEM4LIt/i8cuQSKl/6XKboENwDEBonB5EFqsRogB9VACFNkgFTuCTINKL/9n8+79zO3fcUTLofy9SQbIF1w9j+XQ8VLBgYGRqyxwEXAANmSq/+57Cu+ctuVRPHY5WuSFQaSmQf/8/v1f+SyLf4zcLEgh8sATtvSzyAJYjBILdaAJAcAAGTxKmZBb1QfAAAAAElFTkSuQmCC';
const GREY_PIECE_16 =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAADsOAAA7DgHMtqGDAAAA4ElEQVQ4jWNgoCWwt7fnAGGSNbq6unL7+fnt9fb2/gXCfn5+e0BiRBvg7e1dlpiY+G3q1Kn/QRjE9vHxKcGrycvLK8vb27schH18fC5XV1f/nzZtGhhXVVX99/HxuQSTB6nFZsD/3NxcMM7Pz//f398PNwDEBonB5EFqsRowDaqBEKbIgI6ODvINiImJ+ezn5/fEz89vPckGdHd3//f19X3JwMDAiCsW/uMzYNKkSf/9/Py+enp6Rnl5eWmS5YXm5ub/8fHxH728vP4MXCxMw2WAt7f3Z5AEMRikFmtAkgMAn9VND18JQ1oAAAAASUVORK5CYII=';

export const TRAY_ICONS = {
  normal: BLUE_PIECE_16,
  grey: GREY_PIECE_16,
};

/** Icon payload for a state name; unknown states fall back to `normal`. */
export function trayIcon(state) {
  return TRAY_ICONS[state] ?? TRAY_ICONS.normal;
}
