# PuzzleSolver installer.
#
# Per-user on purpose (DESIGN 11): everything lands under %LOCALAPPDATA% and %APPDATA%
# so no administrator prompt appears, and nothing is written to Program Files or HKLM.
#
# This script is the platform half. The launcher text and the Startup-folder shim are
# generated by app\src\deploy\install.js, which is where the tests live; this file only
# locates paths and launches it.
#
# Executed on windows-latest since #59. What remains unverified is the *unprivileged*
# path, because the runner is an administrator (issue #163).

param(
    # Unattended or scripted installs: install only, do not start the app (and therefore
    # do not open the first-run setup page). All other runs start the app themselves.
    [switch]$NoStart
)

$ErrorActionPreference = 'Stop'

$InstallDir = Join-Path $env:LOCALAPPDATA 'Programs\PuzzleSolver'
Write-Host "Installing PuzzleSolver to $InstallDir"

# If the payload is already the install dir (a re-run), skip the self-copy.
$Source = [IO.Path]::GetFullPath($PSScriptRoot)
$Here = [IO.Path]::GetFullPath($InstallDir)
if ($Source -ne $Here) {
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    Copy-Item -Recurse -Force (Join-Path $PSScriptRoot '*') $InstallDir
}

$Node = Join-Path $InstallDir 'node.exe'
$Deploy = Join-Path $InstallDir 'app\src\deploy\install.js'
if (-not (Test-Path $Node)) { throw "node.exe is missing from $InstallDir" }
if (-not (Test-Path $Deploy)) { throw "app is missing from $InstallDir" }

# Writes PuzzleSolver.vbs, the per-user Startup-folder shim, and the commented example
# config beside where config.toml lives (#181). A user's edited example is kept.
#
# `$ErrorActionPreference = 'Stop'` does not cover a native child's exit code - a
# non-zero exit from node.exe is not a PowerShell error - so it must be checked
# explicitly, or this script prints "Installed" after a failure (#162). The pattern is
# the same one run-smoke.ps1 and run-deploy.ps1 already use.
& $Node $Deploy
if ($LASTEXITCODE -ne 0) {
    throw "PuzzleSolver install failed: node.exe exited with $LASTEXITCODE. Files are in $InstallDir; run PuzzleSolver.vbs to start the app, but it will not start at logon."
}

# Start the app now, so install is one step. Two details matter:
#
#  - It starts PuzzleSolver.vbs, not the per-user Startup shim. The shim sleeps 20 s
#    before delegating (the logon delay); going through it would make the installer
#    appear to hang and then start long after it said it had.
#  - It is detached: Start-Process returns as soon as wscript.exe is created, so the
#    installer exits and the app keeps running. The launcher runs node with a hidden
#    window, so no console flashes.
#
# The `-NoStart` switch is the escape hatch for a scripted install (a package manager,
# an image build, a machine with no interactive desktop), where opening the first-run
# setup page in a browser is wrong. It is off by default because install-and-go is the
# ordinary user path: on a fresh install the app opens its setup page and asks for the
# Pushbullet token (#56).
if ($NoStart) {
    Write-Host "Installed to $InstallDir. It starts at logon; the app was not started now (-NoStart)."
} else {
    $Launcher = Join-Path $InstallDir 'PuzzleSolver.vbs'
    $Wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
    if (-not (Test-Path $Wscript)) { $Wscript = 'wscript.exe' }
    # Quote the launcher: %LOCALAPPDATA% can contain a space (e.g. a username with one).
    Start-Process -FilePath $Wscript -ArgumentList "`"$Launcher`""
    Write-Host "Installed to $InstallDir. It starts at logon, and it is starting now."
}
