# PuzzleSolver installer.
#
# Per-user on purpose (DESIGN 11): everything lands under %LOCALAPPDATA% so no
# administrator prompt appears, and nothing is written to Program Files or HKLM.
#
# This script is the platform half. The task XML, the launcher text and the
# schtasks arguments are generated by app\src\deploy\install.js, which is where the
# tests live; this file only locates paths and launches it.
#
# UNVERIFIED ON WINDOWS: never executed on the Linux development host.

$ErrorActionPreference = 'Stop'

$InstallDir = Join-Path $env:LOCALAPPDATA 'Programs\PuzzleSolver'
Write-Host "Installing PuzzleSolver to $InstallDir"

# If the payload is already the install dir (a re-run), skip the self-copy.
$Source = [IO.Path]::GetFullPath($PSScriptRoot)
$Here = [IO.Path]::GetFullPath($InstallDir)
if ($Source -ne $Here) {
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    Copy-Item -Force (Join-Path $PSScriptRoot 'node.exe') $InstallDir
}

$Node = Join-Path $InstallDir 'node.exe'
$Deploy = Join-Path $InstallDir 'app\src\deploy\install.js'
if (-not (Test-Path $Node)) { throw "node.exe is missing from $InstallDir" }
if (-not (Test-Path $Deploy)) { throw "app is missing from $InstallDir" }

# Writes PuzzleSolver.vbs and registers the logon task (20 s delay, restart on failure).
& $Node $Deploy

Write-Host 'Installed. PuzzleSolver starts at logon; run PuzzleSolver.vbs to start it now.'
