# PuzzleSolver installer.
#
# Per-user on purpose (DESIGN 11): everything lands under %LOCALAPPDATA% and %APPDATA%
# so no administrator prompt appears, and nothing is written to Program Files or HKLM.
#
# This script is the platform half. The launcher text and the Startup-folder shim are
# generated by app\src\deploy\install.js, which is where the tests live; this file only
# locates paths and launches it.
#
# Executed on windows-latest since #59. What remains unverified is the *unprivileged*
# path, because the runner is an administrator (issue #163).

$ErrorActionPreference = 'Stop'

$InstallDir = Join-Path $env:LOCALAPPDATA 'Programs\PuzzleSolver'
Write-Host "Installing PuzzleSolver to $InstallDir"

# If the payload is already the install dir (a re-run), skip the self-copy.
$Source = [IO.Path]::GetFullPath($PSScriptRoot)
$Here = [IO.Path]::GetFullPath($InstallDir)
if ($Source -ne $Here) {
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    Copy-Item -Recurse -Force (Join-Path $PSScriptRoot '*') $InstallDir
}

$Node = Join-Path $InstallDir 'node.exe'
$Deploy = Join-Path $InstallDir 'app\src\deploy\install.js'
if (-not (Test-Path $Node)) { throw "node.exe is missing from $InstallDir" }
if (-not (Test-Path $Deploy)) { throw "app is missing from $InstallDir" }

# Writes PuzzleSolver.vbs and the per-user Startup-folder shim.
#
# `$ErrorActionPreference = 'Stop'` does not cover a native child's exit code - a
# non-zero exit from node.exe is not a PowerShell error - so it must be checked
# explicitly, or this script prints "Installed" after a failure (#162). The pattern is
# the same one run-smoke.ps1 and run-deploy.ps1 already use.
& $Node $Deploy
if ($LASTEXITCODE -ne 0) {
    throw "PuzzleSolver install failed: node.exe exited with $LASTEXITCODE. Files are in $InstallDir; run PuzzleSolver.vbs to start the app, but it will not start at logon."
}

Write-Host "Installed to $InstallDir. It starts at logon; run PuzzleSolver.vbs to start it now."
