' PuzzleSolver launcher - starts the tray app with no console window.
' Generated by src/deploy/launcher.js; edits are overwritten on reinstall.
Option Explicit
Dim fso, shell, env, base, node, script
Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")
Set env = shell.Environment("PROCESS")
base = fso.GetParentFolderName(WScript.ScriptFullName)
node = fso.BuildPath(base, "node.exe")
script = fso.BuildPath(base, "app\src\cli.js")
If Not fso.FileExists(node) Then
  MsgBox "PuzzleSolver is damaged: node.exe is missing from " & base, 16, "PuzzleSolver"
  WScript.Quit 1
End If
shell.CurrentDirectory = base
env("PUZZLESOLVER_LAUNCHER") = WScript.ScriptFullName
shell.Run """" & node & """ """ & script & """ listen", 0, False
