/**
 * The `wscript` launcher shim.
 *
 * A console-subsystem `node.exe` launched from a scheduled task or a shortcut opens
 * a black console window. `wscript` is windowless, and `WScript.Shell.Run` with a
 * window style of `0` starts Node hidden - so the shim is what makes "no console
 * window flashes" true rather than hoped for.
 *
 * The shim is location-independent on purpose: everything is derived from
 * `WScript.ScriptFullName`, so the folder can be moved without regenerating it, and
 * the checked-in `packaging/PuzzleSolver.vbs` can be asserted byte-for-byte against
 * `buildLauncherVbs()`. The quoting rule has one home: `fso.BuildPath` values are
 * wrapped in `"` when handed to `Run`, because a path with a space is the case a
 * naive `base & "\node.exe"` gets wrong.
 *
 * UNVERIFIED ON WINDOWS: no `wscript` exists on this host, so the shim has never been
 * executed. Only its text (and therefore its quoting) is asserted.
 */
import { readFileSync } from 'node:fs';

export const LAUNCHER_FILE = 'PuzzleSolver.vbs';

/**
 * @param {object} [options]
 * @param {string} [options.extraArgs] appended after `listen` (e.g. `--headless`)
 */
export function buildLauncherVbs({ extraArgs = '' } = {}) {
  const args = ['listen', extraArgs].filter(Boolean).join(' ');
  return [
    "' PuzzleSolver launcher - starts the tray app with no console window.",
    "' Generated by src/deploy/launcher.js; edits are overwritten on reinstall.",
    'Option Explicit',
    'Dim fso, shell, base, node, script',
    'Set fso = CreateObject("Scripting.FileSystemObject")',
    'Set shell = CreateObject("WScript.Shell")',
    'base = fso.GetParentFolderName(WScript.ScriptFullName)',
    'node = fso.BuildPath(base, "node.exe")',
    'script = fso.BuildPath(base, "app\\src\\cli.js")',
    'If Not fso.FileExists(node) Then',
    '  MsgBox "PuzzleSolver is damaged: node.exe is missing from " & base, 16, "PuzzleSolver"',
    '  WScript.Quit 1',
    'End If',
    'shell.CurrentDirectory = base',
    // Each path is quoted separately; the concatenation keeps a space in the path
    // from splitting the command line.
    `shell.Run """" & node & """ """ & script & """ ${args}", 0, False`,
    '',
  ].join('\r\n');
}

/** Read the checked-in shim, so a test can assert it matches the generator. */
export function readPackagedLauncher(path) {
  return readFileSync(path, 'utf8');
}

/** Default install location: per-user, so setup needs no administrator. */
export function defaultInstallDir({ platform = process.platform, env = process.env, homedir = null } = {}) {
  if (platform === 'win32') {
    const local = env.LOCALAPPDATA ?? (homedir ? `${homedir}\\AppData\\Local` : '%LOCALAPPDATA%');
    return `${local}\\Programs\\PuzzleSolver`;
  }
  const base = env.XDG_DATA_HOME ?? (homedir ? `${homedir}/.local/share` : '~/.local/share');
  return `${base}/puzzlesolver-app`;
}
