/**
 * The `wscript` launcher shim.
 *
 * A console-subsystem `node.exe` launched from the Startup shim or a shortcut opens
 * a black console window. `wscript` is windowless, and `WScript.Shell.Run` with a
 * window style of `0` starts Node hidden - so the shim is what makes "no console
 * window flashes" true rather than hoped for.
 *
 * The shim is location-independent on purpose: everything is derived from
 * `WScript.ScriptFullName`, so the folder can be moved without regenerating it, and
 * the checked-in `packaging/PuzzleSolver.vbs` can be asserted byte-for-byte against
 * `buildLauncherVbs()`. The quoting rule has one home: `fso.BuildPath` values are
 * wrapped in `"` when handed to `Run`, because a path with a space is the case a
 * naive `base & "\node.exe"` gets wrong.
 *
 * The shim and the startup shim beside it are executed on `windows-latest` since #59;
 * what remains unverified is the *unprivileged* path (see `docs`/DESIGN 11 and #163).
 */
import { readFileSync } from 'node:fs';

export const LAUNCHER_FILE = 'PuzzleSolver.vbs';

/**
 * The startup shim's filename. It sits in the per-user Startup folder, not the install
 * directory, so it is a second generated `.vbs` rather than a copy of the launcher.
 */
export const STARTUP_FILE = 'PuzzleSolver-startup.vbs';

/**
 * The launcher sets this to its own path in the child's environment (#128). It is how
 * the running app knows it was started hidden by the shim, so a restart can go back
 * through the same shim and keep the console hidden (hazard 2). It is deliberately an
 * environment marker, not a CLI flag: flags are validated and could collide, and an
 * installed v0.4 launcher that predates this simply leaves the variable unset.
 */
export const RESTART_LAUNCHER_ENV = 'PUZZLESOLVER_LAUNCHER';

/**
 * @param {object} [options]
 * @param {string} [options.extraArgs] appended after `listen` (e.g. `--headless`)
 */
export function buildLauncherVbs({ extraArgs = '' } = {}) {
  const args = ['listen', extraArgs].filter(Boolean).join(' ');
  return [
    "' PuzzleSolver launcher - starts the tray app with no console window.",
    "' Generated by src/deploy/launcher.js; edits are overwritten on reinstall.",
    'Option Explicit',
    'Dim fso, shell, env, base, node, script',
    'Set fso = CreateObject("Scripting.FileSystemObject")',
    'Set shell = CreateObject("WScript.Shell")',
    'Set env = shell.Environment("PROCESS")',
    'base = fso.GetParentFolderName(WScript.ScriptFullName)',
    'node = fso.BuildPath(base, "node.exe")',
    'script = fso.BuildPath(base, "app\\src\\cli.js")',
    'If Not fso.FileExists(node) Then',
    '  MsgBox "PuzzleSolver is damaged: node.exe is missing from " & base, 16, "PuzzleSolver"',
    '  WScript.Quit 1',
    'End If',
    'shell.CurrentDirectory = base',
    // The marker is how a restart finds the shim again. Set on the process environment
    // before Run, so the child inherits it without a flag the CLI has to understand.
    `env("${RESTART_LAUNCHER_ENV}") = WScript.ScriptFullName`,
    // Each path is quoted separately; the concatenation keeps a space in the path
    // from splitting the command line.
    `shell.Run """" & node & """ """ & script & """ ${args}", 0, False`,
    '',
  ].join('\r\n');
}

/**
 * The per-user Startup-folder shim (issue #163).
 *
 * A scheduled task was refused with `Toegang geweigerd` for an ordinary user:
 * `schtasks /Create` writes into the root task folder, which only an administrator may
 * write. A file in `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` needs no
 * elevation and is already per-user, so it reaches the same "starts at logon" outcome.
 *
 * The task's 20 s logon delay is reproduced here with `WScript.Sleep`; the delay belongs
 * in this shim, not in `PuzzleSolver.vbs`, because the user also runs the launcher by
 * hand and must not wait 20 s for a manual start. The shim delegates to the launcher so
 * the quoting and the `PUZZLESOLVER_LAUNCHER` marker keep one home.
 *
 * @param {object} options
 * @param {string} options.launcherPath full path to `PuzzleSolver.vbs`
 * @param {number} [options.delaySec] logon delay in seconds (default 20)
 */
export function buildStartupVbs({ launcherPath, delaySec = 20 } = {}) {
  if (!launcherPath) throw new Error('buildStartupVbs needs a launcherPath');
  if (!(delaySec >= 0)) throw new Error(`delaySec must be >= 0, got ${delaySec}`);
  return [
    "' PuzzleSolver startup shim - waits, then starts the launcher with no console window.",
    "' Generated by src/deploy/launcher.js; edits are overwritten on reinstall.",
    "' Placed in the per-user Startup folder: no scheduled task, no administrator prompt.",
    'Option Explicit',
    'Dim shell',
    'Set shell = CreateObject("WScript.Shell")',
    // A Windows path cannot contain `"`, so embedding it in a VBS string literal is safe.
    `WScript.Sleep ${delaySec * 1000}`,
    `shell.Run """" & "${launcherPath}" & """", 0, False`,
    '',
  ].join('\r\n');
}

/** Read the checked-in shim, so a test can assert it matches the generator. */
export function readPackagedLauncher(path) {
  return readFileSync(path, 'utf8');
}

/** Default install location: per-user, so setup needs no administrator. */
export function defaultInstallDir({ platform = process.platform, env = process.env, homedir = null } = {}) {
  if (platform === 'win32') {
    const local = env.LOCALAPPDATA ?? (homedir ? `${homedir}\\AppData\\Local` : '%LOCALAPPDATA%');
    return `${local}\\Programs\\PuzzleSolver`;
  }
  const base = env.XDG_DATA_HOME ?? (homedir ? `${homedir}/.local/share` : '~/.local/share');
  return `${base}/puzzlesolver-app`;
}

/**
 * Default autostart location: the per-user Startup folder. `%APPDATA%` is the roaming
 * profile, which is where Start Menu\Programs lives. No elevation is involved.
 */
export function defaultStartupDir({ platform = process.platform, env = process.env, homedir = null } = {}) {
  if (platform === 'win32') {
    const roaming = env.APPDATA ?? (homedir ? `${homedir}\\AppData\\Roaming` : '%APPDATA%');
    return `${roaming}\\Microsoft\\Windows\\Start Menu\\Programs\\Startup`;
  }
  const base = env.XDG_CONFIG_HOME ?? (homedir ? `${homedir}/.config` : '~/.config');
  return `${base}/autostart`;
}
